background:
  concentrations:
    co2:
      backgroundCo2File: ./backgroundCo2Concentrations/background_2018.nc
      localFiles:
      - ./backgroundCo2Concentrations/background_2018.nc
      location: LOCAL
      rename: mix_background
      sha256Values:
      - a8aa37dc87a38572c24065c908762fd0e3e7a449536c18305b2808c6ad29701b
      stationWithoutBackgroundConcentration: DAILYMEAN
      userProvidedBackgroundConcentration: 410
congrad:
  communication_file: ./tmp/LumiaDA-2024-04-26T01_02/LumiaDA-2024-04-26T01_02-congrad.nc
  executable: ${lumiacode.homedir}/src/congrad/congrad.exe
  gradient_norm_reduction: 1.e12
  max_number_of_iterations: 128
correlation:
  inputdir: ./data/corr
emissions:
  '*':
    archive: rclone:lumia:fluxes/nc/
    error_structure: linear
  co2:
    categories:
      biosphere:
        error_min: 0
        is_ocean: false
        localFile: NotApplicable
        origin: VPRM
        tcorr: ${optimize.emissions.co2.biosphere.temporal_correlation}
        unit: PgC
      fossil:
        error_min: 0
        is_ocean: false
        localFile: NotApplicable
        optimize: false
        origin: EDGARv4_LATEST
        tcorr: ${optimize.emissions.co2.fossil.temporal_correlation}
        unit: PgC
      ocean:
        error_min: 0
        is_ocean: true
        localFile: /home/arndt/nateko/data/icos/DICE/fluxes/nc/eurocom025x025/1h/flux_co2.mikaloff01.2018.nc
        localFiles:
        - ./fluxes/nc/eurocom025x025/1h/flux_co2.mikaloff01.2018.nc
        optimize: false
        origin: mikaloff01
        sha256Value:
        - 7a54cc113d12652d93747ac2d2cbc74c34ec2bdaa31f17e5c92e15ee2106b0bc
        tcorr: ${optimize.emissions.co2.ocean.temporal_correlation}
        unit: PgC
    interval: ${run.time.timestep}
    location:
      biosphere: CARBONPORTAL
      fossil: CARBONPORTAL
      ocean: LOCAL
    path: ${run.paths.data}/fluxes/nc/
    prefix: flux_co2.
    region: ${run.grid}
    regionName: ${run.gridname}
  region: ${run.grid}
  regionName: ${run.gridname}
emissions.*.error_structure: linear
lumiacode:
  homedir: /home/arndt/nateko/dev/lumia/lumiaDA/lumia
machineChosen: UNKNOWN
model:
  exec: ${lumiacode.homedir}/transport/multitracer.py
  executable: ${lumia:transport/multitracer.py}
  options:
    serial: false
  output:
    steps:
    - apri
    - apos
  path:
    footprints: ${run.paths.footprints}
    output: ${run.paths.output}
    temp: ${run.paths.temp}
  path_output: ${machine.output}
  path_temp: ${machine.temp}
  transport:
    exec:
      exec: /lumia/transport/multitracer.py
    serial: false
observations:
  co2:
    file:
      dicoveredObsData: ./output/LumiaGUI-2024-04-25T18_20/LumiaGUI-2024-04-25T18_20-DiscoveredObservations.csv
      discoverData: false
      location: CARBONPORTAL
      path: observations-testdata.tar.gz
      ranking:
      - ObsPack
      - Level2
      - Level1
      - NRT
      - AnyOther
      rename: background:mix_background
      selectedObsData: ./output/icosPrep-2024-07-23T09_49/icosPrep-2024-07-23T09_49-selected-ObsData-co2.csv
      selectedPIDs: ./output/icosPrep-2024-07-23T09_49/icosPrep-2024-07-23T09_49-selected-PIDs-co2.csv
      sha256Value: NotApplicable
      tracer: co2
    units: ppm
  end: ${run.time.end}
  file:
    co2:
      discoverData: true
      selectedObsData: None
      selectedPIDs: None
  filters:
    CountriesExcluded: []
    ICOSonly: false
    StationsExcluded:
    - CMN
    - CRA
    - DEC
    - ERS
    - GIC
    - JAR
    - KAS
    - KIT
    - LHW
    - PDM
    - SGC
    - TOH
    - ZSF
    bSamplingHeight: false
    bStationAltitude: false
    inletMaxHeight: 800
    inletMinHeight: 20
    stationMaxAlt: 6500
    stationMinAlt: 30
  start: ${run.time.start}
  uncertainty:
    background: 1.822
    default_weekly_error: 1.5
    dyn:
      freq: 7D
    frequency: dyn
    model: 1.5
    obs_field: err_obs
    setup: false
    systematicErrEstim: 0.5
  validation_file: false
optimize:
  emissions:
    co2:
      biosphere:
        adjust: true
        annual_uncertainty: 0.47 PgC
        npoints: 2500
        optimization_interval: 7d
        spatial_correlation: 500-g
        temporal_correlation: 30D
      fossil:
        adjust: false
      ocean:
        adjust: false
      resample: false
  observations:
    co2:
      uncertainty:
        type: weekly
path:
  data: /data
region: ${run.region}
run:
  grid: ${Grid:{lon0:-15.000,lat0:33.000,lon1:35.000,lat1:73.000,dlon:0.25000, dlat:0.25000}}
  gridname: eurocom025x025
  ncores: 16
  paths:
    data: .
    footprints: /home/arndt/nateko/data/icos/DICE/footprints
    output: ./output/icosPrep-2024-07-23T09_49
    temp: ./tmp/icosPrep-2024-07-23T09_49
  region:
    dlat: 0.25
    dlon: 0.25
    lat0: 33.0
    lat1: 73.0
    lon0: -15.0
    lon1: 35.0
  thisRun:
    PythonVersion: Python environment version is 3.11.9
    hostName: skuggfaxe
    platformArchitecture: x86_64
    platformCore: Linux-6.1.0-21-cloud-amd64-x86_64-with-glibc2.36
    platformFlavour: 1 SMP PREEMPT_DYNAMIC Debian 6.1.90-1 (2024-05-03)
    platformName: Debian GNU/Linux
    platformPrettyName: Debian GNU/Linux 12 (bookworm)
    platformVersion: '12'
    uniqueIdentifierDateTime: 2024-07-23T09_49
    uniqueOutputPrefix: ./output/icosPrep-2024-07-23T09_49/icosPrep-2024-07-23T09_49-
    uniqueTmpPrefix: ./tmp/icosPrep-2024-07-23T09_49/icosPrep-2024-07-23T09_49-
    username: arndt
  time:
    end: '2018-02-01 23:59:59'
    start: '2018-01-01 00:00:00'
    timestep: 1h
  tracers:
  - co2
softwareUsed:
  icosPrep:
    git:
      activeScript: /home/arndt/nateko/dev/py/icosPrep/icosPrep/dataHunting/dataHunter.py
      branch: main
      commit: 1534761fc1c0ee0b5fd5e5338f00f91dc0a5509a
      location: https://github.com/isbjoernen/icosPrep/commit/1534761fc1c0ee0b5fd5e5338f00f91dc0a5509a
      lumiaFlavour: icosPrep
      url: https://github.com/isbjoernen/icosPrep.git
  lumia:
    branch: gitkraken://repolink/778bf0763fae9fad55be85dde4b42613835a3528/branch/LumiaDA?url=git%40github.com%3Alumia-dev%2Flumia.git
    commit: gitkraken://repolink/778bf0763fae9fad55be85dde4b42613835a3528/commit/5e5e9777a227631d6ceeba4fd8cff9b241c55de1?url=git%40github.com%3Alumia-dev%2Flumia.git
    git:
      branch: LumiaDA
      commit: 575cc93f95e84f2f84df0b565a6128de6772e54b
      location: git@github.com:lumia-dev/lumia/commit/575cc93f95e84f2f84df0b565a6128de6772e54b
      url: git@github.com:lumia-dev/lumia.git
  runflex:
    branch: gitkraken://repolink/b9411fbf7aeeb54d7bb34331a98e2cc0b6db9d5f/branch/v2?url=https%3A%2F%2Fgithub.com%2Flumia-dev%2Frunflex.git
    commit: gitkraken://repolink/b9411fbf7aeeb54d7bb34331a98e2cc0b6db9d5f/commit/aad612b36a247046120bda30c8837acb5dec4f26?url=https%3A%2F%2Fgithub.com%2Flumia-dev%2Frunflex.git
    git:
      branch: v2
      commit: 9ef682d69e32fdfd1e1c23e742149c6268b8715a
      location: git@github.com:lumia-dev/runflex/commit/9ef682d69e32fdfd1e1c23e742149c6268b8715a
      url: git@github.com:lumia-dev/runflex.git
tag: ''
thisConfigFile:
  dataformat:
    subversion: 3
    version: 6
transport:
  output: T
  steps: forward
var4d:
  communication:
    file: ./tmp/LumiaDA-2024-04-26T01_02/LumiaDA-2024-04-26T01_02-congrad.nc
  max_iter: 333
